#!/bin/sh

FBSET=`which fbset 2>/dev/null`
if [ -z "${FBSET}" ] ; then
	echo "$0: 'fbset' not found" 1>&2
	exit 1
fi

SUDO=''
[ "${USER}" != 'root' ] && SUDO=/usr/bin/sudo

# ...parse output: ...of `fbset -i`?
set -- ` ${SUDO} ${FBSET} | sed -n '/^mode/,/^endmode/ { /geometry/ { s/.*geometry \([0-9]*\) \([0-9]*\).*/\1 \2/ ; p } }' `
WIDTH=$1
HEIGHT=$2

echo "WIDTH ${WIDTH} x HEIGHT ${HEIGHT}"
